var json=[
	{province:"江苏省",city:
	[
	    {
		 name:"南京市",area:
		 [
		     {
				 name:"秦淮区",qu:[{name:"大商街道"},{name:"大马街道"},{name:"狮子街道"}]
			  },
			  {
				 name:"玄武区",qu:[{name:"青龙街道"},{name:"白虎街道"},{name:"朱雀街道"}]
			  },
			  {
				 name:"浦口区",qu:[{name:"泰山街道"},{name:"沿江街道"},{name:"弘扬街道"}]
			  }
		 ]
		},
		{
		 name:"苏州市",area:
		 [
		     {
				 name:"麻雀区",qu:[{name:"乌鸦街道"},{name:"喜鹊街道"},{name:"鹦鹉街道"}]
			  },
			  {
				 name:"乌鸦区",qu:[{name:"乌龙街道"},{name:"珠子街道"},{name:"竹子街道"}]
			  },
			  {
				 name:"喜鹊区",qu:[{name:"喜鹊街道"},{name:"大龙街道"},{name:"小龙街道"}]
			  }
		 ]
		},
	]
	},
	{province:"安徽省",city:[
	 {
		 name:"巢湖市",area:[
		 {
			 name:"黑鱼区",qu:[{name:"黑鱼大道"},{name:"黑鱼街道"},{name:"飞翔街道"}]
		  },
		  {
			  name:"青鱼区",qu:[{name:"青鱼街道"},{name:"米虾街道"},{name:"螃蟹街道"}]
		  },
		  {
			  name:"扁鱼区",qu:[{name:"青鱼街道"},{name:"米虾街道"},{name:"螃蟹街道"}]
		  }
		 ]
     },
	 {
		 name:"合肥市",area:[
		 {
			 name:"大鱼区",qu:[{name:"黑鱼大道"},{name:"黑鱼街道"},{name:"飞翔街道"}]
		  },
		  {
			  name:"小鱼区",qu:[{name:"青鱼街道"},{name:"米虾街道"},{name:"螃蟹街道"}]
		  },
		  {
			  name:"碎鱼区",qu:[{name:"青鱼街道"},{name:"米虾街道"},{name:"螃蟹街道"}]
		  }
		 ]
      },
	  {
		  name:"马鞍山市",area:[
		 {
			 name:"黑鱼区",qu:[{name:"黑鱼大道"},{name:"黑鱼街道"},{name:"飞翔街道"}]
		  },
		  {
			  name:"青鱼区",qu:[{name:"青鱼街道"},{name:"米虾街道"},{name:"螃蟹街道"}]
		  },
		  {
			  name:"扁鱼区",qu:[{name:"青鱼街道"},{name:"米虾街道"},{name:"螃蟹街道"}]
		  }
		 ]
	  }
	]},
	{province:"湖南省",city:[
	{
		name:"长沙市",area:[
		{
			name:"黄沙区",qu:[{name:"黄沙大道"},{name:"黄沙街道"},{name:"黄沙街道"}]
		},
		{
			name:"白沙区",qu:[{name:"黑鱼大道"},{name:"黑鱼街道"},{name:"飞翔街道"}]
		},
		{
			name:"绿沙区",qu:[{name:"黑鱼大道"},{name:"黑鱼街道"},{name:"飞翔街道"}]
		}
		]
	},
	{name:"湖北市",area:[
		{
			name:"黄沙区",qu:[{name:"黄沙大道"},{name:"黄沙街道"},{name:"黄沙街道"}]
		},
		{
			name:"白沙区",qu:[{name:"黑鱼大道"},{name:"黑鱼街道"},{name:"飞翔街道"}]
		},
		{
			name:"绿沙区",qu:[{name:"黑鱼大道"},{name:"黑鱼街道"},{name:"飞翔街道"}]
		}
		]},
	{name:"肥西市",area:[
		{
			name:"黄沙区",qu:[{name:"黄沙大道"},{name:"黄沙街道"},{name:"黄沙街道"}]
		},
		{
			name:"白沙区",qu:[{name:"黑鱼大道"},{name:"黑鱼街道"},{name:"飞翔街道"}]
		},
		{
			name:"绿沙区",qu:[{name:"黑鱼大道"},{name:"黑鱼街道"},{name:"飞翔街道"}]
		}
		]},
	]
},
]
